/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gesture.based.music.notation.system;

import gesture.based.music.notation.system.music.Editor;

public class App {
        public static void main(String[] args) {
            Editor.main();
    }
}
